jdbc.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=MangaEditorialDB;encrypt=true;trustServerCertificate=true
jdbc.username=SA
jdbc.password=12345
