jdbc.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=MangaEditorialDB;encrypt=true;trustServerCertificate=true

jdbc.username=sa
jdbc.password=123456    