package manga.enums;

public enum NotificationType {
    PROPOSAL_SUBMITTED,
    PROPOSAL_RESOLVED,
    CHAPTER_DEADLINE_ALERT,
    TASK_DUE_REMINDER,
    TASK_OVERDUE,
    TASK_ESCALATED,
    MANUSCRIPT_SUBMITTED,
    MANUSCRIPT_REVIEW_REMINDER,
    MANUSCRIPT_RESOLVED,
    RANKING_PERIOD_OPEN,
    RANKING_CALCULATED,
    DECISION_SESSION_OPENED,
    DECISION_RESOLVED
}
